### ISSUE TITLE
Nommage des composants

### ISSUE THREAD

**Issue by cedric-bidet** [web-id-fr/cms#181]
Dans le CMS, il existe une certaine confusion dans le nommage des composants.

Pour exemple, je veux créer un composant de header de ce type :
<img width="1557" alt="image" src="https://github.com/web-id-fr/cms/assets/5284757/40045c50-3d50-4c06-8086-95f41ca2b48d">

Je vais donc éditer [la page associée](https://web-id.fr/nova/resources/templates/49?tab=Contenu) pour voir quel composant est utilisé.
A l'édition de la page, j'ai ceci :
<img width="1136" alt="image" src="https://github.com/web-id-fr/cms/assets/5284757/6b33ebf1-d491-44f2-a76b-5839c94acc31">

Donc en l'état, ça ne me donne pas l'info du type de composant utilisé.
J'édite le composant de header.
J'ai ceci :
<img width="817" alt="image" src="https://github.com/web-id-fr/cms/assets/5284757/d4f0a734-eecc-4c67-901c-32e344607da4">

Cela me donne l'impression qu'il s'agit du composant "Main Header".
Dans l'idéal, j'aurais aimé pouvoir dupliquer ce composant (mais j'en parle juste après).
Je vais donc dans la liste des composants, et je recherche "Main Header" :
<img width="567" alt="image" src="https://github.com/web-id-fr/cms/assets/5284757/30ceb47f-1e7d-456b-b2d6-26ea2c086a5c">

La recherche ne me trouve rien.
Il faut donc que je retrouve le bon visuel pour pouvoir retrouver le composant associé qui s'appelle en fait "Header principal".
<img width="510" alt="image" src="https://github.com/web-id-fr/cms/assets/5284757/30b42afd-5c6b-45be-b059-cdfa6937037c">

## TODO

- [ ] Lorsque l'on est sur la page d'édition d'un composant, mettre "Header principal" à la place de "Main Header"
- [ ] Lorsque l'on est sur la page d'édition d'une "Page", ajouter le nom du composant sur chacun des composants
- [ ] Lorsque l'on est sur une page d'édition d'un composant, ajouter un bouton "Dupliquer". Dans l'idéal, on duplique le composant (et son contenu) puis on est redirigé vers page d'édition de ce composant nouvellement créé
